# Testing the model

In [33]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
model = load_model('ECG.h5') #loading our trained model

In [89]:
# test model 0
img=image.load_img('/content/data/test/Left Bundle Branch Block/fig_5935.png',target_size=(64,64))#loading image

In [65]:
import numpy as np
x= image.img_to_array(img)
x=np.expand_dims(x,axis=0)

In [66]:
x.shape

(1, 64, 64, 3)

In [67]:
preds=model.predict(x)
pred=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 16ms/step


array([[1., 0., 0., 0., 0., 0.]], dtype=float32)

In [68]:
pred[0]

0

In [69]:
a=model.predict(x)

1/1 [==============================] - 0s 16ms/step


In [70]:
index=['Left Bundle Branch Block','Normal','Premature Atrial Contraction',
       'Premature Ventricular Contractions', 'Right Bundle Branch Block','Ventricular Fibrillation']
result=str(index[pred[0]])
result

'Left Bundle Branch Block'

In [88]:
# test model 1
img=image.load_img('/content/data/test/Normal/fig_2125.png',target_size=(64,64))#loading image

In [50]:
import numpy as np
x= image.img_to_array(img)
x=np.expand_dims(x,axis=0)

In [51]:
x.shape

(1, 64, 64, 3)

In [56]:
preds=model.predict(x)
pred=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 16ms/step


array([[0., 1., 0., 0., 0., 0.]], dtype=float32)

In [53]:
pred[0]

1

In [54]:
a=model.predict(x)

1/1 [==============================] - 0s 14ms/step


In [55]:
index=['Left Bundle Branch Block','Normal','Premature Atrial Contraction',
       'Premature Ventricular Contractions', 'Right Bundle Branch Block','Ventricular Fibrillation']
result=str(index[pred[0]])
result

'Normal'

In [35]:
# test model 2
img=image.load_img('/content/data/test/Premature Atrial Contraction/fig_111.png',target_size=(64,64))#loading image

In [36]:
import numpy as np
x= image.img_to_array(img)
x=np.expand_dims(x,axis=0)

In [37]:
x.shape

(1, 64, 64, 3)

In [38]:
preds=model.predict(x)
pred=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 116ms/step


array([[0., 0., 1., 0., 0., 0.]], dtype=float32)

In [39]:
pred[0]

2

In [40]:
a=model.predict(x)

1/1 [==============================] - 0s 67ms/step


In [41]:
index=['Left Bundle Branch Block','Normal','Premature Atrial Contraction',
       'Premature Ventricular Contractions', 'Right Bundle Branch Block','Ventricular Fibrillation']
result=str(index[pred[0]])
result

'Premature Atrial Contraction'

In [87]:
# test model 3
img=image.load_img('/content/data/test/Premature Ventricular Contractions/VEBfig_18.png',target_size=(64,64))#loading image

In [43]:
import numpy as np
x= image.img_to_array(img)
x=np.expand_dims(x,axis=0)

In [44]:
x.shape

(1, 64, 64, 3)

In [45]:
preds=model.predict(x)
pred=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 16ms/step


array([[0., 0., 0., 1., 0., 0.]], dtype=float32)

In [46]:
pred[0]

3

In [47]:
a=model.predict(x)

1/1 [==============================] - 0s 17ms/step


In [48]:
index=['Left Bundle Branch Block','Normal','Premature Atrial Contraction',
       'Premature Ventricular Contractions', 'Right Bundle Branch Block','Ventricular Fibrillation']
result=str(index[pred[0]])
result

'Premature Ventricular Contractions'

In [86]:
# test model 4
img=image.load_img('/content/data/test/Right Bundle Branch Block/fig_164.png',target_size=(64,64))#loading image

In [58]:
import numpy as np
x= image.img_to_array(img)
x=np.expand_dims(x,axis=0)

In [59]:
x.shape

(1, 64, 64, 3)

In [60]:
preds=model.predict(x)
pred=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 24ms/step


array([[0., 0., 0., 0., 1., 0.]], dtype=float32)

In [61]:
pred[0]

4

In [62]:
a=model.predict(x)

1/1 [==============================] - 0s 24ms/step


In [63]:
index=['Left Bundle Branch Block','Normal','Premature Atrial Contraction',
       'Premature Ventricular Contractions', 'Right Bundle Branch Block','Ventricular Fibrillation']
result=str(index[pred[0]])
result

'Right Bundle Branch Block'

In [85]:
# test model 5
img=image.load_img('/content/data/test/Ventricular Fibrillation/VFEfig_205.png',target_size=(64,64))#loading image

In [79]:
import numpy as np
x= image.img_to_array(img)
x=np.expand_dims(x,axis=0)

In [80]:
x.shape

(1, 64, 64, 3)

In [81]:
preds=model.predict(x)
pred=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 15ms/step


array([[0., 0., 0., 0., 0., 1.]], dtype=float32)

In [82]:
pred[0]

5

In [83]:
a=model.predict(x)

1/1 [==============================] - 0s 15ms/step


In [84]:
index=['Left Bundle Branch Block','Normal','Premature Atrial Contraction',
       'Premature Ventricular Contractions', 'Right Bundle Branch Block','Ventricular Fibrillation']
result=str(index[pred[0]])
result

'Ventricular Fibrillation'